#!/bin/bash

set -e -u -x

if [ "$#" != "2" ]; then
  echo "usage: $0 <path/to/concourse/repo> <rc-version>"
  exit 1
fi

release=$(cd $(dirname $0)/.. && pwd)

dir=${1}
rc=${2}

if ! [ -e $release/dev/base/$rc ]; then
  mkdir -p $release/dev/base/$rc
  curl https://storage.googleapis.com/concourse-artifacts/rcs/concourse-$rc-linux-amd64.tgz | \
    tar -C $release/dev/base/$rc -zxf -
fi

docker run -v $dir:/src -v $release:/release --entrypoint /release/dev/build-concourse-inner concourse/dev $rc
