#!/bin/bash

set -e -u

cd $(dirname $0)/..
source ./dev/common.bash

ran_by="true"

by "building concourse from source..."
pushd /src
  go install github.com/gobuffalo/packr/packr
  packr build \
    -o /release/dev/base/concourse/bin/concourse \
    ./bin/cmd/concourse
popd

by "creating dev.tgz..."
mkdir -p /release/src/concourse
tar -C /release/dev/base -czf /release/src/concourse/dev.tgz concourse
echo done
