#!/bin/bash

set -e -u -x

if [ "$#" != "2" ]; then
  echo "usage: $0 <path/to/concourse/repo> <rc-version>"
  exit 1
fi

release=$(cd $(dirname $0)/.. && pwd)

dir=${1}
rc=${2}

if ! [ -e $release/dev/base/$rc ]; then
  mkdir -p $release/dev/base/$rc
  curl https://storage.googleapis.com/concourse-artifacts/rcs/concourse-$rc-linux-amd64.tgz | \
    tar -C $release/dev/base/$rc -zxf -
fi

pushd $dir
  go install github.com/gobuffalo/packr/packr
  GOOS=linux GOARCH=amd64 packr build \
    -o $release/dev/base/$rc/concourse/bin/concourse \
    ./bin/cmd/concourse
popd

tar -C $release/dev/base/$rc -czf $release/src/concourse/dev.tgz concourse
