#!/bin/bash

set -e -u

cd $(dirname $0)/..
source ./dev/common.bash

if [ "$#" != "1" ]; then
  echo "usage: $0 <path/to/concourse/repo>"
  exit 1
fi

src=${1}

by "syncing blobs..."
bosh sync-blobs

by "extracting current rc..."
rm -rf ./dev/base
mkdir -p ./dev/base
tar -C ./dev/base -zxf blobs/concourse/concourse-*-linux-ubuntu-amd64.tgz
echo done

docker run -v $src:/src -v $(pwd):/release --entrypoint /release/dev/build-concourse-inner concourse/dev
