#!/bin/bash

set -e -u
shopt -s nullglob

cd $(dirname $0)

ops=(
  --ops-file=bosh-deployment/virtualbox/cpi.yml
  --ops-file=bosh-deployment/virtualbox/outbound-network.yml
  --ops-file=bosh-deployment/bosh-lite.yml
  --ops-file=bosh-deployment/bosh-lite-runc.yml
  --ops-file=bosh-deployment/jumpbox-user.yml
)

for o in local-ops/*.yml; do
  ops+=("--ops-file=$o")
done

bosh ${1}-env bosh-deployment/bosh.yml \
  --state ./state.json \
  --vars-store ./creds.yml \
  -v director_name="Bosh Lite Director" \
  -v internal_ip=192.168.50.6 \
  -v internal_gw=192.168.50.1 \
  -v internal_cidr=192.168.50.0/24 \
  -v outbound_network_name=NatNetwork \
  "${ops[@]}"
