#!/bin/bash

set -e -u

source $(dirname $0)/common.bash

cd $(dirname $0)/../..

./dev/vbox/upload

by "deploying concourse-test..."
bosh -n -e vbox \
  -d concourse \
  deploy ./manifests/single-vm.yml \
  --vars-store dev/vbox/deploy-creds.yml \
  -v concourse_version=latest \
  -v deployment_name=concourse \
  -v garden_runc_version=latest \
  -v network_name=test \
  -v vm_type=test \
  -v web_ip=10.244.15.2 \
  "$@"
