#!/bin/bash

set -e -u

cd $(dirname $0)/../..
source ./dev/common.bash

./dev/vbox/deploy

by "running testflight..."
cd ./src/github.com/concourse/testflight
ATC_URL="http://10.244.15.2:8080" \
ATC_USERNAME="test" \
ATC_PASSWORD="test" \
  ginkgo -r -p -nodes=3 "$@"
