#!/bin/bash

set -e -u

cd $(dirname $0)/../..
source ./dev/common.bash

export BOSH_ENVIRONMENT="192.168.50.6"
export BOSH_CLIENT="admin"
export BOSH_CLIENT_SECRET="$(bosh int ./dev/vbox/creds.yml --path /admin_password)"
export BOSH_CA_CERT="$(bosh int ./dev/vbox/creds.yml --path /director_ssl/ca)"

by "force-creating dev release..."
bosh create-release --force

by "uploading release..."
bosh -e vbox upload-release

by "running topgun..."
cd ../concourse/topgun
ginkgo -p "$@"
