#!/bin/bash

set -e -u

source $(dirname $0)/common.bash

cd $(dirname $0)/../..

by "force-creating dev release..."
bosh create-release --force

by "uploading release..."
bosh -e vbox upload-release
